return {}

-- return {
--   'akinsho/bufferline.nvim',
--   version = '*',
--   dependencies = 'nvim-tree/nvim-web-devicons',
--   config = function()
--     vim.opt.termguicolors = true
--     require('bufferline').setup {
--       options = {
--         offsets = {
--           {
--             filetype = 'neo-tree',
--             text_align = 'left',
--           },
--         },
--         diagnostics = 'nvim_lsp',
--         show_close_icon = false,
--       },
--     }
--   end,
-- }
